// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh0XkRt20pzW7gCp0y0-9EiCg5DRevtu8',
    appId: '1:75291800404:ios:a07222a9ba334095510ec1',
    messagingSenderId: '75291800404',
    projectId: 'bookswap-879ad',
    storageBucket: 'bookswap-879ad.firebasestorage.app',
    iosClientId: '75291800404-ccppmpdtgg317bc2ncon0837rjt9ug8h.apps.googleusercontent.com',
    iosBundleId: 'vmug',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvI-t3ADUSFWder77ymzpyEN3meKotxG4',
    appId: '1:75291800404:web:3bed125bf6da27d3510ec1',
    messagingSenderId: '75291800404',
    projectId: 'bookswap-879ad',
    authDomain: 'bookswap-879ad.firebaseapp.com',
    storageBucket: 'bookswap-879ad.firebasestorage.app',
    measurementId: 'G-TX0SLVE382',
  );

}